// Generated by gencpp from file dockerpublisher/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef DOCKERPUBLISHER_MESSAGE_ADDTWOINTSRESPONSE_H
#define DOCKERPUBLISHER_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dockerpublisher
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : greeting()  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : greeting(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _greeting_type;
  _greeting_type greeting;





  typedef boost::shared_ptr< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::dockerpublisher::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::dockerpublisher::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::dockerpublisher::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.greeting == rhs.greeting;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator1> & lhs, const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dockerpublisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af3498ba158bcdd555fe81847eb6e16d";
  }

  static const char* value(const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf3498ba158bcdd5ULL;
  static const uint64_t static_value2 = 0x55fe81847eb6e16dULL;
};

template<class ContainerAllocator>
struct DataType< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dockerpublisher/AddTwoIntsResponse";
  }

  static const char* value(const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string greeting\n"
;
  }

  static const char* value(const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.greeting);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dockerpublisher::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "greeting: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.greeting);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOCKERPUBLISHER_MESSAGE_ADDTWOINTSRESPONSE_H
