// Generated by gencpp from file dockerpublisher/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DOCKERPUBLISHER_MESSAGE_ADDTWOINTS_H
#define DOCKERPUBLISHER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <dockerpublisher/AddTwoIntsRequest.h>
#include <dockerpublisher/AddTwoIntsResponse.h>


namespace dockerpublisher
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace dockerpublisher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dockerpublisher::AddTwoInts > {
  static const char* value()
  {
    return "4d4778d28f323c1d92882d79624c0c0f";
  }

  static const char* value(const ::dockerpublisher::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::dockerpublisher::AddTwoInts > {
  static const char* value()
  {
    return "dockerpublisher/AddTwoInts";
  }

  static const char* value(const ::dockerpublisher::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::dockerpublisher::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::dockerpublisher::AddTwoInts >
template<>
struct MD5Sum< ::dockerpublisher::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dockerpublisher::AddTwoInts >::value();
  }
  static const char* value(const ::dockerpublisher::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dockerpublisher::AddTwoIntsRequest> should match
// service_traits::DataType< ::dockerpublisher::AddTwoInts >
template<>
struct DataType< ::dockerpublisher::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::dockerpublisher::AddTwoInts >::value();
  }
  static const char* value(const ::dockerpublisher::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dockerpublisher::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::dockerpublisher::AddTwoInts >
template<>
struct MD5Sum< ::dockerpublisher::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dockerpublisher::AddTwoInts >::value();
  }
  static const char* value(const ::dockerpublisher::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dockerpublisher::AddTwoIntsResponse> should match
// service_traits::DataType< ::dockerpublisher::AddTwoInts >
template<>
struct DataType< ::dockerpublisher::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::dockerpublisher::AddTwoInts >::value();
  }
  static const char* value(const ::dockerpublisher::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOCKERPUBLISHER_MESSAGE_ADDTWOINTS_H
