// Generated by gencpp from file esp32communication/canResponse.msg
// DO NOT EDIT!


#ifndef ESP32COMMUNICATION_MESSAGE_CANRESPONSE_H
#define ESP32COMMUNICATION_MESSAGE_CANRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace esp32communication
{
template <class ContainerAllocator>
struct canResponse_
{
  typedef canResponse_<ContainerAllocator> Type;

  canResponse_()
    : response()  {
    }
  canResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::esp32communication::canResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esp32communication::canResponse_<ContainerAllocator> const> ConstPtr;

}; // struct canResponse_

typedef ::esp32communication::canResponse_<std::allocator<void> > canResponse;

typedef boost::shared_ptr< ::esp32communication::canResponse > canResponsePtr;
typedef boost::shared_ptr< ::esp32communication::canResponse const> canResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esp32communication::canResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esp32communication::canResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esp32communication::canResponse_<ContainerAllocator1> & lhs, const ::esp32communication::canResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esp32communication::canResponse_<ContainerAllocator1> & lhs, const ::esp32communication::canResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esp32communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::esp32communication::canResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32communication::canResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32communication::canResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32communication::canResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32communication::canResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32communication::canResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esp32communication::canResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::esp32communication::canResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::esp32communication::canResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esp32communication/canResponse";
  }

  static const char* value(const ::esp32communication::canResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esp32communication::canResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
;
  }

  static const char* value(const ::esp32communication::canResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esp32communication::canResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct canResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esp32communication::canResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esp32communication::canResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESP32COMMUNICATION_MESSAGE_CANRESPONSE_H
